[package]
name = "dcz"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version="4.5.40", features=["derive"] }
iced-x86 = { version="1.21.0", features=["code_asm"] }
object = { version="0.37.1", features=["build", "write"] }

